### ISSUE TITLE
Making the App Responsive and Look Awesome on Mobile Devices

### ISSUE THREAD

**Issue by BillyMassey** [fleawig/splurty#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

**Comment by fleawig** [comment]
Hey Billy -- thanks for pointing that out. I was checking the responsive view locally but totally missed this!

I saw in the bootstrap documentation that I need to add this meta tag in the <head> :
<meta name="viewport" content="width=device-width, initial-scale=1">

I'll add this and then push up to my git and heroku repositories. Because of the time difference here in Berlin, I'm away from my computer until tomorrow morning (my time), but I will do it first thing. 
I'll add another comment here when it's completed. 

Best,
Jesse

**Comment by fleawig** [comment]
Oh funny -- I guess these comments don't show HTML (I had pasted the code in above. Maybe it'll show up below.)

meta name="viewport" content="width=device-width, initial-scale=1"

**Comment by fleawig** [comment]
OK, I added that meta tag and pushed up to git and heroku. Works on my phone now. Thanks again for pointing that out!
